#spring.application.name=DokodaPepper
#DB接続設定
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/DokodaPepper
spring.datasource.username = postgres
spring.datasource.password = admin

spring.jpa.hibernate.ddl-auto = none
#hibernateの機能でEntityからDDLを自動実行するかの設定。今回はnone

#spring.jpa.properties.hibernate.format_sql = true
#コンソールにログで出力されるSQLを整形する設定

spring.sql.init.encoding = UTF-8
#DDLスクリプトを読み込む際のエンコーディング指定

logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder = TRACE
#コンソールにログでSQLとバインドパラメータが出力されるようにする設定

spring.security.user.name=user
spring.security.user.password=pass


#google api key
my.api.key=AIzaSyDFnkZnQ9ToZOFFaolAdhk23kOUeRZmbXo


